Vagrant.configure("2") do |config|
  # Specify the box you want to use
  config.vm.box = "bento/rockylinux-9"

  # Configure a private network with a static IP
  config.vm.network "private_network", ip: "10.10.10.10"
  config.vm.network "forwarded_port", guest: 80, host: 8088
  config.vm.network "public_network", bridge: "en7: Thunderbolt Ethernet Slot 1", ip: "172.27.0.40"

  config.vm.provision "shell", inline: <<-SHELL
    sudo yum install httpd -y
    sudo systemctl start httpd
  SHELL


  # Other configurations can go here
end