all:
  hosts:
    hub:
      ansible_host: 10.200.0.10
    node0:
      ansible_host: 10.200.0.11
    node1:
      ansible_host: 10.200.0.12

  vars:
    

hubs:
  hosts:
    hub:

nodes:
  hosts:
    node0:
    node1:
