- hosts: all
  become: true
  vars:
    server_file_hash: bde3bda5017170711e799631df978510de9176dafafb5fd2ea59b2923f654c91
  tasks:
    - name: Install Java 17
      yum:
        name: java-17-openjdk
        state: present
    
    - name: Download selenium server 4.25
      get_url:
        url: https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.25.0/selenium-server-4.25.0.jar
        dest: /opt/selenium-server.jar
        mode: '0755'
    
    - name: Calculate downloaded file's hash
      shell: "sha256sum /opt/selenium-server.jar | awk '{ print $1 }'"
      register: calculated_checksum
    - debug:
        msg: "calculated: {{ calculated_checksum }}"
    - debug:
        msg: "calculated stdout: {{ calculated_checksum.stdout }}"
    
    - name: Validate server file hash
      assert:
        that:
          - calculated_checksum.stdout == server_file_hash
        fail_msg: Downloaded file's has doesn't match expected value.

- hosts: hub
  become: true
  tasks:
    - name: Create selenium hub service
      copy: 
        dest: /etc/systemd/system/selenium-hub.service
        content: |
          [Unit]
          Description=Selenium Hub service
          After=network.target

          [Service]
          ExecStart=/usr/bin/java -jar /opt/selenium-server.jar hub

          [Install]
          WantedBy=multi-user.target
    
    - name: Enable and start Selenium service
      systemd:
        name: selenium-hub
        enabled: yes
        state: started

- hosts: node
  become: true
  tasks:
    - name: Create selenium node service
      copy: 
        dest: /etc/systemd/system/selenium-node.service
        content: |
          [Unit]
          Description=Selenium Node service
          After=network.target

          [Service]
          ExecStart=/usr/bin/java -jar /opt/selenium-server.jar node --hub http://10.200.0.10:4444

          [Install]
          WantedBy=multi-user.target
    
    - name: Enable and start Selenium service
      systemd:
        name: selenium-node
        enabled: yes
        state: started


